# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-04 07:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BranchInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('branch_name', models.CharField(max_length=30)),
                ('from_build', models.CharField(max_length=40)),
                ('to_build', models.CharField(max_length=40)),
            ],
            options={
                'verbose_name': 'branch',
                'db_table': 'branch_info',
                'ordering': ['branch_name'],
            },
        ),
        migrations.CreateModel(
            name='ChangeInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('affected_file', models.CharField(max_length=200)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bluefish.BranchInfo')),
            ],
            options={
                'db_table': 'change_info',
            },
        ),
    ]
