# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-04 07:54
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bluefish', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='branchinfo',
            table='gi_branch',
        ),
        migrations.AlterModelTable(
            name='changeinfo',
            table='gi_change',
        ),
    ]
