# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-07 05:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bluefish', '0002_auto_20151203_2354'),
    ]

    operations = [
        migrations.RenameField(
            model_name='changeinfo',
            old_name='affected_file',
            new_name='file_path',
        ),
        migrations.AddField(
            model_name='changeinfo',
            name='file_name',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
    ]
