# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-03-04 13:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bluefish', '0004_auto_20151218_1809'),
    ]

    operations = [
        migrations.AddField(
            model_name='branchinfo',
            name='layer',
            field=models.CharField(default='SYP', max_length=60),
        ),
        migrations.AddField(
            model_name='changeinfo',
            name='current_version',
            field=models.CharField(default='#', max_length=30),
        ),
    ]
