# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-18 10:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bluefish', '0003_auto_20151206_2144'),
    ]

    operations = [
        migrations.AlterField(
            model_name='changeinfo',
            name='file_name',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='changeinfo',
            name='file_path',
            field=models.CharField(max_length=230),
        ),
    ]
