# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-04 07:53
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('issues', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='issues',
            table='gi_issue',
        ),
        migrations.AlterModelTable(
            name='solutions',
            table='gi_solution',
        ),
    ]
