# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-07 05:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('issues', '0002_auto_20151203_2353'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issues',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
